# Generated by Django 4.1.3 on 2022-11-22 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='target_end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Target End Date'),
        ),
    ]
