# Generated by Django 4.1.3 on 2022-12-05 18:38

from django.db import migrations, models
import django_resized.forms
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retirement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Retirement Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[250, 250], upload_to=products.models.get_product_image_location),
        ),
    ]
