# Generated by Django 4.1.3 on 2023-01-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_key',
            field=models.CharField(max_length=110, null=True, verbose_name='Product Key'),
        ),
    ]
